INCLUDE Biblioteca_5D.lib
.MODEL SMALL
.STACK
.DATA
RUTACARPETARAIZ     DB 'C:\BUNKER ACCESS',0
RUTACARPETAANDRICK  DB 'C:\BUNKER ACCESS\ANDRICK NATIVIDAD',0
RUTACARPETAGILMAR   DB 'C:\BUNKER ACCESS\GILMAR GALLAGA',0
RUTACARPETALUCIA    DB 'C:\BUNKER ACCESS\LUCIA GALINDO',0

;ANDRICK: USUARIOS, BITACORASALIDA 
;GILMAR: BITACORAENTRADA,REPORTEEXTERIOR
;LUCIA; ALIMENTOS,
RUTAUSUARIOS        DB 'C:\BUNKER ACCESS\ANDRICK NATIVIDAD\Users.txt',0
RUTABITACORASALIDA  DB 'C:\BUNKER ACCESS\ANDRICK NATIVIDAD\BitacoraSalida.txt',0 

RUTABITACORAENTRADA DB 'C:\BUNKER ACCESS\GILMAR GALLAGA\BitacoraReingreso.txt',0
RUTAREPORTEEXTE     DB 'C:\BUNKER ACCESS\GILMAR GALLAGA\ReporteExterior.txt',0

RUTAALIMENTOS       DB 'C:\BUNKER ACCESS\LUCIA GALINDO\Alimentos.txt',0
RUTACHEQUEO         DB 'C:\BUNKER ACCESS\LUCIA GALINDO\ChequeoMedico.txt',0

MSJCREARCARPETA    DB ' PRESIONA UNA TECLA PARA PODER CREAR ' 
MSJCREARCARPETADOS DB 'EL DIRECTORI DE CARPETAS DEL PROYECTO'
msjCarpetaSI       db "Carpetas y Archivos creados correctamente"
msjCarpetaNo       db 'ERROR: al crear la carpeta           '

msjArchivoNo       db 'ERROR: al crear el archivo           '


.CODE
INICIO:
MOV AX,DATA
MOV ES,AX
MOV DS,AX 

IMP_COLOR MSJCREARCARPETA,37,0,0,14,14,2EH 
IMP_COLOR MSJCREARCARPETADOS,37,0,0,15,14,2EH 
RASTREO
;CREACION DE CARPETAS
CREAR_CARPETA RUTACARPETARAIZ
JC ERROR_CARPETA

CREAR_CARPETA RUTACARPETAANDRICK
JC ERROR_CARPETA

CREAR_CARPETA RUTACARPETAGILMAR
JC ERROR_CARPETA

CREAR_CARPETA RUTACARPETALUCIA
JC ERROR_CARPETA 


;CREACION DE ARCHIVOS
;ANDRICK: USUARIOS, BITACORASALIDA
CREAR_ARCHIVO RUTAUSUARIOS,32
JC ERROR_ARCHIVO

CREAR_ARCHIVO RUTABITACORASALIDA,32
JC ERROR_ARCHIVO
 
 
;GILMAR: BITACORAENTRADA,REPORTEEXTERIOR
CREAR_ARCHIVO RUTABITACORAENTRADA,32
JC ERROR_ARCHIVO
 
 CREAR_ARCHIVO RUTAREPORTEEXTE,32
JC ERROR_ARCHIVO
 
;LUCIA; ALIMENTOS,
CREAR_ARCHIVO RUTAALIMENTOS,32
JC ERROR_ARCHIVO

CREAR_ARCHIVO RUTACHEQUEO,32
JC ERROR_ARCHIVO

JMP CORRECTO
 





ERROR_CARPETA:
IMP_COLOR msjCarpetaNo,24,0,0,22,18,4EH 

ERROR_ARCHIVO:
IMP_COLOR msjArchivoNo,24,0,0,22,18,4EH

CORRECTO:
IMP_COLOR msjCarpetaSI,41,0,0,22,12,2EH
RASTREO



FIN:
MOV AX,4C00H
INT 21H



